{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "dd923556",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pokemon Roster: ['pikachu', 'axew', 'psyduck', 'cubone', 'natu']\n",
      "Move Options: dict_keys(['surf', 'thunderbolt', 'iron tail', 'agility'])\n",
      "********************\n",
      "Choose an attack Pikachu:\n",
      "Pikachu uses surf on Axew!\n",
      "surf does regular damage.\n",
      "It's not very effective.\n",
      "Axew took 35 damage. Health is now 68.5.\n",
      "********************\n",
      "Move Options: dict_keys(['dragon claw', 'crunch', 'stomping tantrum', 'leer'])\n",
      "********************\n",
      "Choose an attack Axew:\n",
      "Axew uses dragon claw on Pikachu!\n",
      "dragon claw does boosted damage.\n",
      "It's effective\n",
      "Pikachu took 81 damage. Health is now 0.\n",
      "Pikachu has fainted.\n",
      "********************\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "from random import randint\n",
    "\n",
    "\n",
    "class Pokemon:\n",
    "    \"\"\"\n",
    "    A base class for a generic pokemon\n",
    "    \n",
    "    Attributes (Public)\n",
    "    -------------------\n",
    "    name : str\n",
    "        The name of the pokemon\n",
    "    level : int\n",
    "        The level of the pokemon that is used to determine its stats\n",
    "    status : str\n",
    "        The status of the pokemon as fainted or ready, indicating if it can battle\n",
    "    current_health : int\n",
    "        The current health of the pokemon throughout the battle\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, name, primary_type, secondary_type, \n",
    "                 attack, defense, sp_attack, sp_defense, health, speed, level=1):\n",
    "        \"\"\"\n",
    "        Establishes the relevant information for the pokemon what will be used when making calculations\n",
    "        and displaying output\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        name : str\n",
    "            The name of the pokemon\n",
    "        primary_type : str\n",
    "            The primary typing of the pokemon that will determine its type matchups\n",
    "        secondary_type : str\n",
    "            The secondary typing of the pokemon that will determine its type matchups\n",
    "        attack : int\n",
    "            The base attack stat of the pokemon as an integer\n",
    "        defense : int\n",
    "            The base defense stat of the pokemon as an integer\n",
    "        sp_attack : int\n",
    "            The base special attack stat of the pokemon as an integer\n",
    "        sp_defense : int\n",
    "            The base special defense stat of the pokemon as an integer\n",
    "        health : int\n",
    "            The base health stat of the pokemon as an integer\n",
    "        speed : int\n",
    "            The base speed stat of the pokemon as an integer\n",
    "        level : int\n",
    "            The level of the pokemon as an integer\n",
    "        \"\"\"\n",
    "        self.name = name\n",
    "        # Base stats and type were made private because they shouldn't be altered outside of the class\n",
    "        self.__type = (primary_type, secondary_type)\n",
    "        self.level = level\n",
    "        self.__base_attack = attack\n",
    "        self.__base_defense = defense\n",
    "        self.__base_special_attack = sp_attack\n",
    "        self.__base_special_defense = sp_defense\n",
    "        self.__base_health = health\n",
    "        self.__base_speed = speed\n",
    "        self.status = \"Ready\"\n",
    "        # The following attributes are protected but not private so that they can be accessed easily by the\n",
    "        # superclasses to be added onto or overridden while still showing that they should only be used \n",
    "        # internally\n",
    "        self._moves = {\n",
    "            \"placeholder1\": {\"power\": 50, \"type\": primary_type, \"attack_type\": \"Physical\", \"accuracy\": 100},\n",
    "            \"placeholder2\": {\"power\": 50, \"type\": primary_type, \"attack_type\": \"Special\", \"accuracy\": 100},\n",
    "            \"placeholder3\": {\"target\": \"attack\", \"factor\": 1.5, \"type\": primary_type, \"attack type\": \"Status\", \"accuracy\": 100}\n",
    "        }\n",
    "        self.__calculate_stats()\n",
    "        self._weaknesses = []\n",
    "        self._resistances = []\n",
    "        self._double_weaknesses = []\n",
    "        self._double_resistances = []\n",
    "        self._immunities = []\n",
    "        \n",
    "    def __calculate_stats(self):\n",
    "        \"\"\"\n",
    "        Calculates the effective stats of the pokemon using its base stats and level\n",
    "        \"\"\"\n",
    "        # Stats were made private so they couldn't be altered mid-battle while current health was made\n",
    "        # public so it could update as the battle progressed\n",
    "        self.__attack = math.floor(((2 * self.__base_attack * self.level) / 100) + 10)\n",
    "        self.__defense = math.floor(((2 * self.__base_defense * self.level) / 100) + 10)\n",
    "        self.__special_attack = math.floor(((2 * self.__base_special_attack * self.level) / 100) + 10)\n",
    "        self.__special_defense = math.floor(((2 * self.__base_special_defense * self.level) / 100) + 10)\n",
    "        self.__health = math.floor(self.__base_health + 2 * self.level)\n",
    "        self.__speed = math.floor(self.__base_speed + 2 * self.level)\n",
    "        self.current_health = self.__health\n",
    "\n",
    "    def produce_attack(self, other_pokemon, attack_name):\n",
    "        \"\"\"\n",
    "        Generic attack method for all pokemon\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        other_pokemon : Instance of a Pokemon subclass\n",
    "            The pokemon receiving the move\n",
    "        attack_name : str\n",
    "            The name of the attack being used that will determine the move's attributes for damage\n",
    "            calculations and output\n",
    "        \"\"\"\n",
    "        attack_name = attack_name.lower()\n",
    "        if self.status == \"Fainted\":\n",
    "            print(\"Pokemon is fainted and can't attack\")\n",
    "        else:\n",
    "            # Setting attack attributes\n",
    "            move = self._moves[attack_name]\n",
    "            attack_type = move[\"type\"]\n",
    "            attack_attack_type = move[\"attack type\"]\n",
    "            accuracy = move[\"accuracy\"]\n",
    "            hit = randint(1, 100)\n",
    "            if hit > accuracy:\n",
    "                print(\"********************\")\n",
    "                print(f\"Choose an attack {self.name}:\")\n",
    "                print(\"The attack missed.\")\n",
    "            else:\n",
    "                # Conditionals determine how damage will be calculated and what the outputted text will be\n",
    "                # based on the chosen attack's attributes\n",
    "                if attack_attack_type == \"Physical\" or attack_attack_type == \"Special\":\n",
    "                    power = move[\"power\"]\n",
    "                    if attack_attack_type == \"Physical\":\n",
    "                        attack = self.get_stat(\"attack\")\n",
    "                        other_defense = other_pokemon.get_stat(\"defense\")\n",
    "                    elif attack_attack_type == \"Special\":\n",
    "                        attack = self.get_stat(\"special attack\")\n",
    "                        other_defense = other_pokemon.get_stat(\"special defense\")\n",
    "                    damage = math.floor(((0.5 * (attack / other_defense) * power) + 1))\n",
    "                    if attack_type in self.get_type():\n",
    "                        damage += math.floor(0.2 * damage)\n",
    "                    other_pokemon.take_damage(damage, attack_type)\n",
    "                    print(\"********************\")\n",
    "                    print(f\"Choose an attack {self.name}:\")\n",
    "                    print(f\"{self.name} uses {attack_name} on {other_pokemon.name}!\")\n",
    "                    if attack_type in self.get_type():\n",
    "                        print(f\"{attack_name} does boosted damage.\")\n",
    "                    else:\n",
    "                        print(f\"{attack_name} does regular damage.\")\n",
    "                    if attack_type in other_pokemon.get_weaknesses() or attack_type in other_pokemon.get_double_weaknesses():\n",
    "                        print(\"It's super effective!\")\n",
    "                    elif attack_type in other_pokemon.get_resistances() or attack_type in other_pokemon.get_double_resistances():\n",
    "                        print(\"It's not very effective.\")\n",
    "                    elif attack_type in other_pokemon.get_immunities():\n",
    "                        print(f\"It doesn't affect {other_pokemon.name}.\")\n",
    "                    else:\n",
    "                        print(\"It's effective\")\n",
    "                    if attack_type in other_pokemon.get_immunities():\n",
    "                        print(f\"{other_pokemon.name} took no damage.\")\n",
    "                    else:\n",
    "                        print(f\"{other_pokemon.name} took {damage} damage. Health is now {other_pokemon.current_health}.\")\n",
    "                    if other_pokemon.status == \"Fainted\":\n",
    "                        print(f\"{other_pokemon.name} has fainted.\")\n",
    "                    print(\"********************\")\n",
    "                    # Creates the basic logic for stat lowering status moves\n",
    "                elif attack_attack_type == \"Status\":\n",
    "                    target_stat = move[\"target\"]\n",
    "                    factor = move[\"factor\"]\n",
    "                    if factor < 1:\n",
    "                        new_value = other_pokemon.get_stat(target_stat) * factor\n",
    "                        other_pokemon.set_stat(target_stat, new_value)\n",
    "                        print(f\"Choose an attack {self.name}:\")\n",
    "                        print(f\"{self.name} uses {attack_name} on {other_pokemon.name}!\")\n",
    "                        print(f\"{other_pokemon.name}'s {target_stat} was lowered.\")\n",
    "                        print(\"********************\")\n",
    "                    elif factor > 1:\n",
    "                        new_value = self.get_stat(target_stat) * factor\n",
    "                        self.set_stat(target_stat, new_value)\n",
    "                        print(f\"Choose an attack {self.name}:\")\n",
    "                        print(f\"{self.name} uses {attack_name} on {other_pokemon.name}!\")\n",
    "                        print(f\"{self.name} raised its {target_stat}.\")\n",
    "                        print(\"********************\")\n",
    "\n",
    "    def take_damage(self, damage, attack_type):\n",
    "        \"\"\"\n",
    "        Generic method for taking damage for all pokemon\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        damage : int\n",
    "            The damage being inflicted as an integer\n",
    "        attack_type : str\n",
    "            The type of the move being used that will determine its effectiveness and damage multiplier\n",
    "        \"\"\"\n",
    "        # Conditionals determine damage multiplier based on the type matchup of the pokemon and move\n",
    "        if attack_type in self.get_weaknesses():\n",
    "            damage *= 2\n",
    "        elif attack_type in self.get_double_weaknesses():\n",
    "            damage *= 4\n",
    "        elif attack_type in self.get_resistances():\n",
    "            damage *= 0.5\n",
    "        elif attack_type in self.get_double_resistances():\n",
    "            damage *= 0.25\n",
    "        elif attack_type in self.get_immunities():\n",
    "            damage = 0\n",
    "        self.current_health -= damage\n",
    "        if self.current_health <= 0:\n",
    "            self.status = \"Fainted\"\n",
    "            self.current_health = 0\n",
    "\n",
    "    def show_health(self):\n",
    "        \"\"\"\n",
    "        Prints the current health stat of the pokemon\n",
    "        \"\"\"\n",
    "        print(\"********************\")\n",
    "        print(f\"Name: {self.name}\")\n",
    "        print(f\"Health: {self.current_health}\")\n",
    "        print(\"********************\")\n",
    "    \n",
    "    def get_stat(self, stat):\n",
    "        \"\"\"\n",
    "        Finds the desired private stat of the pokemon\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        stat : str\n",
    "            The stat being acquired by the method\n",
    "            \n",
    "        Returns\n",
    "        -------\n",
    "        __attack : int\n",
    "            The attack stat that is returned if attack was entered as the desired stat\n",
    "        __defense : int\n",
    "            The defense stat that is returned if defense was entered as the desired stat\n",
    "        __special_attack : int\n",
    "            The special attack stat that is returned if special attack was entered as the desired stat\n",
    "        __special_defense : int\n",
    "            The special defense stat that is returned if special defense was entered as the desired stat\n",
    "        __speed : int\n",
    "            The speed stat that is returned if speed was entered as the desired stat\n",
    "        \"\"\"\n",
    "        # Allows stats to be displayed while still being private\n",
    "        stat = stat.lower()\n",
    "        if stat == \"attack\":\n",
    "            return self.__attack\n",
    "        elif stat == \"defense\":\n",
    "            return self.__defense\n",
    "        elif stat == \"special attack\":\n",
    "            return self.__special_attack\n",
    "        elif stat == \"special defense\":\n",
    "            return self.__special_defense\n",
    "        elif stat == \"speed\":\n",
    "            return self.__speed\n",
    "        else:\n",
    "            print(\"Not valid stat\")\n",
    "            \n",
    "    def set_stat(self, stat, value):\n",
    "        \"\"\"\n",
    "        Changes the value of the desired stat to the new value inputted\n",
    "        \n",
    "        Paramters\n",
    "        ---------\n",
    "        stat : str\n",
    "            The stat that will be changed\n",
    "        value : int\n",
    "            The new numerical value being given to the stat\n",
    "        \"\"\"\n",
    "        # Allows stats to be changes while still being private\n",
    "        if value <= 0:\n",
    "            print(\"Impossible value\")\n",
    "        else:\n",
    "            if stat == \"attack\":\n",
    "                self.__attack = value\n",
    "            elif stat == \"defense\":\n",
    "                self.__defense = value\n",
    "            elif stat == \"special attack\":\n",
    "                self.__special_attack = value\n",
    "            elif stat == \"special defense\":\n",
    "                self.__special_defense = value\n",
    "            elif stat == \"speed\":\n",
    "                self.__speed = value\n",
    "            else:\n",
    "                print(\"Not valid stat\")\n",
    "                \n",
    "    def get_type(self):\n",
    "        \"\"\"\n",
    "        Finds the type of the pokemon\n",
    "        \n",
    "        Returns\n",
    "        -------\n",
    "        __type : tuple\n",
    "            The type of the pokemon\n",
    "        \"\"\"\n",
    "        return self.__type\n",
    "    \n",
    "    # Get functions are created despite the attributes being protected and not private because \n",
    "    # they should only be changed in the class itself\n",
    "    \n",
    "    def get_weaknesses(self):\n",
    "        \"\"\"\n",
    "        Finds the weaknesses of the pokemon\n",
    "        \n",
    "        Returns\n",
    "        -------\n",
    "        _weaknesses : list\n",
    "            The weaknesses of the pokemon\n",
    "        \"\"\"\n",
    "        return self._weaknesses\n",
    "    \n",
    "    def get_resistances(self):\n",
    "        \"\"\"\n",
    "        Finds the resistances of the pokemon\n",
    "        \n",
    "        Returns\n",
    "        -------\n",
    "        _resistances : list\n",
    "            The resistances of the pokemon\n",
    "        \"\"\"\n",
    "        return self._resistances\n",
    "    \n",
    "    def get_double_weaknesses(self):\n",
    "        \"\"\"\n",
    "        Finds the double weaknesses of the pokemon\n",
    "        \n",
    "        Returns\n",
    "        -------\n",
    "        _double_weaknesses : list\n",
    "            The double weaknesses of the pokemon\n",
    "        \"\"\"\n",
    "        return self._double_weaknesses\n",
    "    \n",
    "    def get_double_resistances(self):\n",
    "        \"\"\"\n",
    "        Finds the double resistances of the pokemon\n",
    "        \n",
    "        Returns\n",
    "        -------\n",
    "        _double_resistances : list\n",
    "            The double resistances of the pokemon\n",
    "        \"\"\"\n",
    "        return self._double_resistances\n",
    "    \n",
    "    def get_immunities(self):\n",
    "        \"\"\"\n",
    "        Finds the immunities of the pokemon\n",
    "        \n",
    "        Returns\n",
    "        -------\n",
    "        _immunities : list\n",
    "            The immunities of the pokemon\n",
    "        \"\"\"\n",
    "        return self._immunities\n",
    "\n",
    "# All the pokemon's base stats, moves, typings, and type matchups were taken from the games themselves\n",
    "\n",
    "class Pikachu(Pokemon):\n",
    "    \"\"\"\n",
    "    A subclass of Pokemon for the Pikachu species\n",
    "    \n",
    "    Attributes (Public)\n",
    "    -------------------\n",
    "    name : str\n",
    "        The name of the pokemon, Pikachu\n",
    "    level : int\n",
    "        The level of the Pikachu that is used to determine its stats\n",
    "    status : str\n",
    "        The status of the Pikachu as fainted or ready, indicating if it can battle\n",
    "    current_health : int\n",
    "        The current health of the Pikachu throughout the battle\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, level):\n",
    "        \"\"\"\n",
    "        Plugs in Pikachu's information into the base pokemon initialization method, establishes its type\n",
    "        matchups, and overrides the placeholder moves with a Pikachu specific moveset\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        level : int\n",
    "            The level of the Pikachu as an integer\n",
    "        \"\"\"\n",
    "        Pokemon.__init__(self, \"Pikachu\", \"Electric\", \"None\",\n",
    "                         55, 40, 50, 50, 35, 90, level)\n",
    "        self._moves = {\n",
    "            \"surf\": {\"power\": 60, \"type\": \"Water\", \"attack type\": \"Special\", \"accuracy\": 100}, \n",
    "            \"thunderbolt\": {\"power\": 60, \"type\": \"Electric\", \"attack type\": \"Special\", \"accuracy\": 100},\n",
    "            \"iron tail\": {\"power\": 100, \"type\": \"Steel\", \"attack type\": \"Physical\", \"accuracy\": 75},\n",
    "            \"agility\": {\"target\": \"speed\", \"factor\": 2, \"type\": \"Psychic\", \"attack type\": \"Status\", \"accuracy\": 100}\n",
    "        }\n",
    "        self._weaknesses.append(\"Ground\")\n",
    "        self._resistances.extend([\"Electric\", \"Flying\", \"Steel\"])\n",
    "        \n",
    "    def produce_attack(self, other_pokemon, attack_name):\n",
    "        \"\"\"\n",
    "        Uses the base pokemon produce attack function and adds extra conditionals to accounts for the\n",
    "        potential stat changes from the move iron tail\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "         other_pokemon : Instance of a Pokemon subclass\n",
    "            The pokemon receiving the move\n",
    "        attack_name : str\n",
    "            The name of the attack being used that will determine the move's attributes for damage\n",
    "            calculations, outputs, and additional effects\n",
    "        \"\"\"\n",
    "        Pokemon.produce_attack(self, other_pokemon, attack_name)\n",
    "        # Accounts for iron tail's 30% chance of lowering defense by one stage\n",
    "        if attack_name.lower() == \"iron tail\" and other_pokemon.status != \"Fainted\":\n",
    "            chance = randint(1, 100)\n",
    "            if chance > 70:\n",
    "                new_defense = other_pokemon.get_stat(\"defense\") * 0.67\n",
    "                other_pokemon.set_stat(\"defense\", new_defense)\n",
    "                print(f\"{other_pokemon.name}'s defense has been lowered.'\")\n",
    "                print(\"********************\")\n",
    "\n",
    "class Axew(Pokemon):\n",
    "    \"\"\"\n",
    "    A subclass of Pokemon for the Axew species\n",
    "    \n",
    "    Attributes (Public)\n",
    "    -------------------\n",
    "    name : str\n",
    "        The name of the pokemon, Axew\n",
    "    level : int\n",
    "        The level of the Axew that is used to determine its stats\n",
    "    status : str\n",
    "        The status of the Axew as fainted or ready, indicating if it can battle\n",
    "    current_health : int\n",
    "        The current health of the Axew throughout the battle\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, level):\n",
    "        \"\"\"\n",
    "        Plugs in Axew's information into the base pokemon initialization method, establishes its type\n",
    "        matchups, and overrides the placeholder moves with an Axew specific moveset\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        level : int\n",
    "            The level of the Axew as an integer\n",
    "        \"\"\"\n",
    "        Pokemon.__init__(self, \"Axew\", \"Dragon\", \"None\",\n",
    "                         87, 60, 30, 40, 46, 57, level)\n",
    "        self._moves = {\n",
    "            \"dragon claw\": {\"power\": 80, \"type\": \"Dragon\", \"attack type\": \"Physical\", \"accuracy\": 100}, \n",
    "            \"crunch\": {\"power\": 80, \"type\": \"Dark\", \"attack type\": \"Physical\", \"accuracy\": 100},\n",
    "            \"stomping tantrum\": {\"power\": 75, \"type\": \"Ground\", \"attack type\": \"Physical\", \"accuracy\": 100},\n",
    "            \"leer\": {\"target\": \"defense\", \"factor\": 0.67, \"type\": \"Normal\", \"attack type\": \"Status\", \"accuracy\": 100}\n",
    "        }\n",
    "        self._weaknesses.extend([\"Dragon\", \"Ice\", \"Fairy\"])\n",
    "        self._resistances.extend([\"Electric\", \"Fire\", \"Water\", \"Grass\"])\n",
    "        \n",
    "    def produce_attack(self, other_pokemon, attack_name):\n",
    "        \"\"\"\n",
    "        Uses the base pokemon produce attack function and adds extra conditionals to accounts for the\n",
    "        potential stat changes from the move crunch\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "         other_pokemon : Instance of a Pokemon subclass\n",
    "            The pokemon receiving the move\n",
    "        attack_name : str\n",
    "            The name of the attack being used that will determine the move's attributes for damage\n",
    "            calculations, outputs, and additional effects\n",
    "        \"\"\"\n",
    "        Pokemon.produce_attack(self, other_pokemon, attack_name)\n",
    "        # Accounts for crunch's 20% chance of lowering defense by one stage\n",
    "        if attack_name.lower() == \"crunch\" and other_pokemon.status != \"Fainted\":\n",
    "            chance = randint(1, 100)\n",
    "            if chance > 80:\n",
    "                new_defense = other_pokemon.get_stat(\"defense\") * 0.67\n",
    "                other_pokemon.set_stat(\"defense\", new_defense)\n",
    "                print(f\"{other_pokemon.name}'s defense has been lowered.'\")\n",
    "                print(\"********************\")\n",
    "                        \n",
    "class Psyduck(Pokemon):\n",
    "    \"\"\"\n",
    "    A subclass of Pokemon for the Psyduck species\n",
    "    \n",
    "    Attributes (Public)\n",
    "    -------------------\n",
    "    name : str\n",
    "        The name of the pokemon, Psyduck\n",
    "    level : int\n",
    "        The level of the Psyduck that is used to determine its stats\n",
    "    status : str\n",
    "        The status of the Psyduck as fainted or ready, indicating if it can battle\n",
    "    current_health : int\n",
    "        The current health of the Psyduck throughout the battle\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, level):\n",
    "        \"\"\"\n",
    "        Plugs in Psyduck's information into the base pokemon initialization method, establishes its type\n",
    "        matchups, and overrides the placeholder moves with a Psyduck specific moveset\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        level : int\n",
    "            The level of the Psyduck as an integer\n",
    "        \"\"\"\n",
    "        Pokemon.__init__(self, \"Psyduck\", \"Water\", \"None\",\n",
    "                         52, 48, 65, 50, 50, 55, level)\n",
    "        self._moves = {\n",
    "            \"aqua tail\": {\"power\": 90, \"type\": \"Water\", \"attack type\": \"Physical\", \"accuracy\": 90}, \n",
    "            \"blizzard\": {\"power\": 110, \"type\": \"Ice\", \"attack type\": \"Special\", \"accuracy\": 70},\n",
    "            \"psychic\": {\"power\": 90, \"type\": \"Psychic\", \"attack type\": \"Special\", \"accuracy\": 100},\n",
    "            \"amnesisa\": {\"target\": \"special defense\", \"factor\": 2, \"type\": \"Psychic\", \"attack type\": \"Status\", \"accuracy\": 100}\n",
    "        }\n",
    "        self._weaknesses.extend([\"Grass\", \"Electric\"])\n",
    "        self._resistances.extend([\"Water\", \"Fire\", \"Steel\", \"Ice\"])\n",
    "        \n",
    "    def produce_attack(self, other_pokemon, attack_name):\n",
    "        \"\"\"\n",
    "        Uses the base pokemon produce attack function and adds extra conditionals to accounts for the\n",
    "        potential stat changes from the move psychic\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "         other_pokemon : Instance of a Pokemon subclass\n",
    "            The pokemon receiving the move\n",
    "        attack_name : str\n",
    "            The name of the attack being used that will determine the move's attributes for damage\n",
    "            calculations, outputs, and additional effects\n",
    "        \"\"\"\n",
    "        Pokemon.produce_attack(self, other_pokemon, attack_name)\n",
    "        # Accounts for psychic's 10% chance of loweing special defense by one stage\n",
    "        if attack_name.lower() == \"psychic\" and other_pokemon.status != \"Fainted\" and \"Psychic\" not in other_pokemon.get_immunities():\n",
    "            chance = randint(1, 100)\n",
    "            if chance > 90:\n",
    "                new_special_defense = other_pokemon.get_stat(\"special defense\") * 0.67\n",
    "                other_pokemon.set_stat(\"special defense\", new_special_defense)\n",
    "                print(f\"{other_pokemon.name}'s special defense has been lowered.'\")\n",
    "                print(\"********************\")\n",
    "\n",
    "class Cubone(Pokemon):\n",
    "    \"\"\"\n",
    "    A subclass of Pokemon for the Cubone species\n",
    "    \n",
    "    Attributes (Public)\n",
    "    -------------------\n",
    "    name : str\n",
    "        The name of the pokemon, Cubone\n",
    "    level : int\n",
    "        The level of the Cubone that is used to determine its stats\n",
    "    status : str\n",
    "        The status of the Cubone as fainted or ready, indicating if it can battle\n",
    "    current_health : int\n",
    "        The current health of the Cubone throughout the battle\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, level):\n",
    "        \"\"\"\n",
    "        Plugs in Cubone's information into the base pokemon initialization method, establishes its type\n",
    "        matchups, and overrides the placeholder moves with a Cubone specific moveset\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        level : int\n",
    "            The level of the Cubone as an integer\n",
    "        \"\"\"\n",
    "        Pokemon.__init__(self, \"Cubone\", \"Ground\", \"None\",\n",
    "                         50, 95, 40, 50, 50, 35, level)\n",
    "        self._moves = {\n",
    "            \"bulldoze\": {\"power\": 60, \"type\": \"Ground\", \"attack type\": \"Physical\", \"accuracy\": 100}, \n",
    "            \"flamethrower\": {\"power\": 90, \"type\": \"Fire\", \"attack type\": \"Special\", \"accuracy\": 100},\n",
    "            \"brick break\": {\"power\": 75, \"type\": \"Fighting\", \"attack type\": \"Physical\", \"accuracy\": 100},\n",
    "            \"iron defense\": {\"target\": \"defense\", \"factor\": 2, \"type\": \"Steel\", \"attack type\": \"Status\", \"accuracy\": 100}\n",
    "        }\n",
    "        self._weaknesses.extend([\"Grass\", \"Water\", \"Ice\"])\n",
    "        self._resistances.extend([\"Poison\", \"Rock\"])\n",
    "        self._immunities.append(\"Electric\")\n",
    "        \n",
    "    def produce_attack(self, other_pokemon, attack_name):\n",
    "        \"\"\"\n",
    "        Uses the base pokemon produce attack function and adds extra conditionals to accounts for the\n",
    "        additional stat changes from the move bulldoze\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "         other_pokemon : Instance of a Pokemon subclass\n",
    "            The pokemon receiving the move\n",
    "        attack_name : str\n",
    "            The name of the attack being used that will determine the move's attributes for damage\n",
    "            calculations, outputs, and additional effects\n",
    "        \"\"\"\n",
    "        Pokemon.produce_attack(self, other_pokemon, attack_name)\n",
    "        # Accounts for bulldoze always lowering speed by one stage\n",
    "        if attack_name.lower() == \"bulldoze\" and other_pokemon.status != \"Fainted\" and \"Ground\" not in other_pokemon.get_immunities():\n",
    "            new_speed = other_pokemon.get_stat(\"speed\") * 0.67\n",
    "            other_pokemon.set_stat(\"speed\", new_speed)\n",
    "            print(f\"{other_pokemon.name}'s speed has been lowered.'\")\n",
    "            print(\"********************\")\n",
    "                        \n",
    "class Natu(Pokemon):\n",
    "    \"\"\"\n",
    "    A subclass of Pokemon for the Natu species\n",
    "    \n",
    "    Attributes (Public)\n",
    "    -------------------\n",
    "    name : str\n",
    "        The name of the pokemon, Natu\n",
    "    level : int\n",
    "        The level of the Natu that is used to determine its stats\n",
    "    status : str\n",
    "        The status of the Natu as fainted or ready, indicating if it can battle\n",
    "    current_health : int\n",
    "        The current health of the Natu throughout the battle\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, level):\n",
    "        \"\"\"\n",
    "        Plugs in Natu's information into the base pokemon initialization method, establishes its type\n",
    "        matchups, and overrides the placeholder moves with a Natu specific moveset\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "        level : int\n",
    "            The level of the Natu as an integer\n",
    "        \"\"\"\n",
    "        Pokemon.__init__(self, \"Natu\", \"Psychic\", \"Flying\",\n",
    "                         50, 45, 70, 45, 40, 70, level)\n",
    "        self._moves = {\n",
    "            \"psychic\": {\"power\": 90, \"type\": \"Psychic\", \"attack type\": \"Special\", \"accuracy\": 100}, \n",
    "            \"aerial ace\": {\"power\": 60, \"type\": \"Flying\", \"attack type\": \"Physical\", \"accuracy\": 100},\n",
    "            \"ominous wind\": {\"power\": 60, \"type\": \"Ghost\", \"attack type\": \"Special\", \"accuracy\": 100},\n",
    "            \"dazzling gleam\": {\"power\": 80, \"type\": \"Fairy\", \"attack type\": \"Special\", \"accuracy\": 100}\n",
    "        }\n",
    "        self._weaknesses.extend([\"Electric\", \"Ice\", \"Rock\", \"Ghost\", \"Dark\"])\n",
    "        self._resistances.extend([\"Grass\", \"Psychic\"])\n",
    "        self._double_resistances.append(\"Fighting\")\n",
    "        self._immunities.append(\"Ground\")\n",
    "        \n",
    "    def produce_attack(self, other_pokemon, attack_name):\n",
    "        \"\"\"\n",
    "        Uses the base pokemon produce attack function and adds extra conditionals to accounts for the\n",
    "        potential stat changes from the moves ominous wind and psychic\n",
    "        \n",
    "        Parameters\n",
    "        ----------\n",
    "         other_pokemon : Instance of a Pokemon subclass\n",
    "            The pokemon receiving the move\n",
    "        attack_name : str\n",
    "            The name of the attack being used that will determine the move's attributes for damage\n",
    "            calculations, outputs, and additional effects\n",
    "        \"\"\"\n",
    "        Pokemon.produce_attack(self, other_pokemon, attack_name)\n",
    "        # Accounts for ominous wind's 10$ chance of raising all of the pokemon's stats by one stage and \n",
    "        # psychic's 10% chance of loweing special defense by one stage\n",
    "        if attack_name.lower() == \"ominous wind\" and other_pokemon.status != \"Fainted\" and \"Ghost\" not in other_pokemon.get_immunities():\n",
    "            boost = randint(1, 100)\n",
    "            if boost > 90:\n",
    "                stats_to_raise = [\"attack\", \"defense\", \"special attack\", \"special defense\", \"speed\"]\n",
    "                for stat in stats_to_raise:\n",
    "                    new_stat = self.get_stat(stat) * 1.5\n",
    "                    self.set_stat(stat, new_stat)\n",
    "                print(f\"All of {self.name}'s stats have been raised.\")\n",
    "                print(\"********************\")\n",
    "        elif attack_name.lower() == \"psychic\" and other_pokemon.status != \"Fainted\" and \"Psychic\" not in other_pokemon.get_immunities():\n",
    "            chance = randint(1, 100)\n",
    "            if chance > 90:\n",
    "                new_special_defense = other_pokemon.get_stat(\"special defense\") * 0.67\n",
    "                other_pokemon.set_stat(\"special defense\", new_special_defense)\n",
    "                print(f\"{other_pokemon.name}'s special defense has been lowered.'\")\n",
    "                print(\"********************\")\n",
    "                        \n",
    "def main():\n",
    "    \"\"\"\n",
    "    Conatins all the logic of the program that allows for the game to be played\n",
    "    \"\"\"\n",
    "    pokemon_roster = [\"pikachu\", \"axew\", \"psyduck\", \"cubone\", \"natu\"]\n",
    "    # While loops are used to ensure that a valid option is inputted before conitnuing, preventing\n",
    "    # potential crashes\n",
    "    print(f\"Pokemon Roster: {pokemon_roster}\")\n",
    "    while True:\n",
    "        pokemon = input(\"Player 1, choose your pokemon! \")\n",
    "        if pokemon.lower() in pokemon_roster:\n",
    "            while True:\n",
    "                level = int(input(\"What leverl is it? (1-100) \"))\n",
    "                if level > 100 or level < 1:\n",
    "                    print(\"Invalid. Level must be a number between 1 and 100.\")\n",
    "                else:\n",
    "                    break\n",
    "            break\n",
    "        else:\n",
    "            print(\"Ivalid pokemon. Please select from the roster.\")\n",
    "    if pokemon == \"Pikachu\" or pokemon == \"pikachu\":\n",
    "        pokemon1 = Pikachu(level)\n",
    "    elif pokemon == \"Axew\" or pokemon == \"axew\":\n",
    "        pokemon1 = Axew(level)\n",
    "    elif pokemon == \"Psyduck\" or pokemon == \"psyduck\":\n",
    "        pokemon1 = Psyduck(level)\n",
    "    elif pokemon == \"Cubone\" or pokemon == \"cubone\":\n",
    "        pokemon1 = Cubone(level)\n",
    "    elif pokemon == \"Natu\" or pokemon == \"natu\":\n",
    "        pokemon1 = Natu(level)\n",
    "    while True:\n",
    "        pokemon = input(\"Player 2, choose your pokemon! \")\n",
    "        if pokemon.lower() in pokemon_roster:\n",
    "            while True:\n",
    "                level = int(input(\"What leverl is it? (1-100) \"))\n",
    "                if level > 100 or level < 1:\n",
    "                    print(\"Invalid. Level must be between 1 and 100.\")\n",
    "                else:\n",
    "                    break\n",
    "            break\n",
    "        else:\n",
    "            print(\"Ivalid pokemon. Please select from the roster\")\n",
    "    if pokemon == \"Pikachu\" or pokemon == \"pikachu\":\n",
    "        pokemon2 = Pikachu(level)\n",
    "    elif pokemon == \"Axew\" or pokemon == \"axew\":\n",
    "        pokemon2 = Axew(level)\n",
    "    elif pokemon == \"Psyduck\" or pokemon == \"psyduck\":\n",
    "        pokemon2 = Psyduck(level)\n",
    "    elif pokemon == \"Cubone\" or pokemon == \"cubone\":\n",
    "        pokemon2 = Cubone(level)\n",
    "    elif pokemon == \"Natu\" or pokemon == \"natu\":\n",
    "        pokemon2 = Natu(level)\n",
    "    # Main while loop makes the battle continue until a pokemon faints and other while loope ensure\n",
    "    # valid options are inputted\n",
    "    # Current health is shown at the end of bother players' turns to update them on their pokemon's status\n",
    "    while pokemon1.status == \"Ready\" and pokemon2.status == \"Ready\":\n",
    "        if pokemon1.get_stat(\"speed\") > pokemon2.get_stat(\"speed\"):\n",
    "            print(f\"Move Options: {pokemon1._moves.keys()}\")\n",
    "            while True:\n",
    "                attack1 = input(\"Player 1, choose your move: \")\n",
    "                if attack1.lower() in pokemon1._moves.keys():\n",
    "                    pokemon1.produce_attack(pokemon2, attack1)\n",
    "                    break\n",
    "                else:\n",
    "                    print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "            if pokemon2.status == \"Fainted\":\n",
    "                break\n",
    "            print(f\"Move Options: {pokemon2._moves.keys()}\")\n",
    "            while True:\n",
    "                attack2 = input(\"Player 2, choose your move: \")\n",
    "                if attack2.lower() in pokemon2._moves.keys():\n",
    "                    pokemon2.produce_attack(pokemon1, attack2)\n",
    "                    break\n",
    "                else:\n",
    "                    print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "            if pokemon1.status == \"Fainted\":\n",
    "                break\n",
    "            pokemon1.show_health()\n",
    "            pokemon2.show_health()\n",
    "        elif pokemon1.get_stat(\"speed\") < pokemon2.get_stat(\"speed\"):\n",
    "            print(f\"Move Options: {pokemon2._moves.keys()}\")\n",
    "            while True:\n",
    "                attack2 = input(\"Player 2, choose your move: \")\n",
    "                if attack2.lower() in pokemon2._moves.keys():\n",
    "                    pokemon2.produce_attack(pokemon1, attack2)\n",
    "                    break\n",
    "                else:\n",
    "                    print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "            if pokemon1.status == \"Fainted\":\n",
    "                break\n",
    "            print(f\"Move Options: {pokemon1._moves.keys()}\")\n",
    "            while True:\n",
    "                attack1 = input(\"Player 1, choose your move: \")\n",
    "                if attack1.lower() in pokemon1._moves.keys():\n",
    "                    pokemon1.produce_attack(pokemon2, attack1)\n",
    "                    break\n",
    "                else:\n",
    "                    print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "            if pokemon2.status == \"Fainted\":\n",
    "                break\n",
    "            pokemon1.show_health()\n",
    "            pokemon2.show_health()\n",
    "        else:\n",
    "            turn = randint(1, 2)\n",
    "            if turn == 1:\n",
    "                print(f\"Move Options: {pokemon1._moves.keys()}\")\n",
    "                while True:\n",
    "                    attack1 = input(\"Player 1, choose your move: \")\n",
    "                    if attack1.lower() in pokemon1._moves.keys():\n",
    "                        pokemon1.produce_attack(pokemon2, attack1)\n",
    "                        break\n",
    "                    else:\n",
    "                        print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "                if pokemon2.status == \"Fainted\":\n",
    "                    break\n",
    "                print(f\"Move Options: {pokemon2._moves.keys()}\")\n",
    "                while True:\n",
    "                    attack2 = input(\"Player 2, choose your move: \")\n",
    "                    if attack2.lower() in pokemon2._moves.keys():\n",
    "                        pokemon2.produce_attack(pokemon1, attack2)\n",
    "                        break\n",
    "                    else:\n",
    "                        print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "                if pokemon1.status == \"Fainted\":\n",
    "                    break\n",
    "                pokemon1.show_health()\n",
    "                pokemon2.show_health()\n",
    "            elif turn == 2:\n",
    "                print(f\"Move Options: {pokemon2._moves.keys()}\")\n",
    "                while True:\n",
    "                    attack2 = input(\"Player 2, choose your move: \")\n",
    "                    if attack2.lower() in pokemon2._moves.keys():\n",
    "                        pokemon2.produce_attack(pokemon1, attack2)\n",
    "                        break\n",
    "                    else:\n",
    "                        print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "                if pokemon1.status == \"Fainted\":\n",
    "                    break\n",
    "                print(f\"Move Options: {pokemon1._moves.keys()}\")\n",
    "                while True:\n",
    "                    attack1 = input(\"Player 1, choose your move: \")\n",
    "                    if attack1.lower() in pokemon1._moves.keys():\n",
    "                        pokemon1.produce_attack(pokemon2, attack1)\n",
    "                        break\n",
    "                    else:\n",
    "                        print(f\"Invalid. Available moves are {pokemon1._moves.keys()}\")\n",
    "                if pokemon2.status == \"Fainted\":\n",
    "                    break\n",
    "                pokemon1.show_health()\n",
    "                pokemon2.show_health()\n",
    "            \n",
    "main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
